version: '3'

services:
  blog:
    build:
      dockerfile: Dockerfile
        environment:
          CONFIG: DevelopmentConfig
          SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://app:password@pg:5432/blog
        volumes:
          - ./:/app
        ports:
          - "5000:5000"
        depends_on:
          - pg

  blog-prod:
    build:
      context: .
      dockerfile: ./docker-build/blog/Dockerfile
      environment:
        CONFIG: ProductionConfig
        SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://app:password@pg:5432/blog
      ports:
        - "5080:80"
      depends_on:
        - pg

  pg:
    image: postgres # use latest official postgres version
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
    volumes:
      - pg-data:/var/lib/postgresql/data/ # persist data even if container shuts down


volumes:
  pg-data: